name: hedgehog
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2>=2.16
  - pip=19.3.1
  - gofasta
  # - usher
  - mafft>=7.475
  - snakemake-minimal=7.24.0
  - pip:
    - git+https://github.com/cov-lineages/pangolin.git
