name: hedgehog
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - minimap2>=2.16
  - biopython >=1.74
  - pip=19.3.1
  - python>=3.7
  - gofasta
  - mafft
  - snakemake-minimal=7.24.0
  - pip:
    - git+https://github.com/cov-lineages/pangolin.git
