name: hedgehog
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_hedgehog_test:
    name: hedgehog test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: hedgehog
          channels: conda-forge,bioconda,defaults
          conda-version: "4.12.0"
          miniforge-variant: Mambaforge
      - name: Install hedgehog
        run: pip install -e .
      - name: Check hedgehog version
        run: hedgehog --version
      - name: Run hedgehog with test data
        run: hedgehog hedgehog/tests/test.fasta  2>&1 | tee hedgehog.log
        
