name: hedgehog
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}
jobs:
  run_hedgehog_test:
    name: Hedgehog test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: hedgehog
          channels: conda-forge,bioconda,defaults
          python-version: "3.10"
          conda-version: "23.3"
          mamba-version: "1.1"
      - name: Install hedgehog
        run: pip install -e .
      - name: Check hedgehog version
        run: hedgehog --version
      - name: Run hedgehog with test data
        run: hedgehog hedgehog/tests/test.fasta  2>&1 | tee hedgehog.log
        
